### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by levaly** [chungkwong/MathOCR#2]
Is there a way to contact the developer?

**Comment by chungkwong** [comment]
I was the developer, but I am not working on that now because the problem is much harder than I thought, I had completely failed to make it a bit useful.

**Comment by levaly** [comment]
Can you please elaborate more?
—
Lev Alyshayev

**Comment by chungkwong** [comment]
No known free software can do that well neither. For nonfree software, as I know, only InftyReader claim that they can recognize well-scanned scientific document.

**Comment by levaly** [comment]
can we discuss over skype?

**Comment by chungkwong** [comment]
I am sorry, but I cannot speak fluency english.

**Comment by levaly** [comment]
skype chat will be fine. I have a couples of quetsions for you. I am available at levalyshayev
