### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by learnerhouse** [chungkwong/MathOCR#3]
when I use command like java -jar original-mathocr-1.0-SNAPSHOT.jar , It doesn't work and return original-mathocr-1.0-SNAPSHOT.jar 中没有主清单属性 , how can I use it with GUI?

**Comment by chungkwong** [comment]
The Main-Class property is fixed in 098b58524d58c88b979267dfccc80a9dcfeb6ecf, build instructions and a link to a pre-built JAR is added in README.md:

> ## Usage
> 
> ### Prebuilt JAR
> 
> A prebuilt JAR is available at https://oss.sonatype.org/content/repositories/snapshots/com/github/chungkwong/mathocr/1.0-SNAPSHOT
> 
> ### Build from source
> 
> 1. Clone the project: `https://github.com/chungkwong/MathOCR.git`
> 2. Get into the directory: `cd MathOCR`
> 3. Edit the file `src/test/resources/com/github/chungkwong/mathocr/text/math_train_set.xml`
>     - Ensure that path to the fonts are correct
>     - Ensure all the characters needed to be recognized are listed
> 4. Train the model: `mvn exec:java -Dexec.mainClass="com.github.chungkwong.mathocr.text.ModelBuilder" -Dexec.classpathScope="test"`
> 5. Link or copy the model to the project: `ln -s ~/.mathocr/default/ src/main/resources/com/github/chungkwong/mathocr/character/default`
> 6. Build the JAR: `mvn package`
> 
> ### Run
> 
> Run the JAR file by double click or something like `java -jar mathocr-1.0-SNAPSHOT.jar`,
> then a GUI interface should appear.
