### ISSUE TITLE
fonts目录的文件在哪能找到？？

### ISSUE THREAD

**Issue by lvxin0315** [chungkwong/MathOCR#4]
![image](https://user-images.githubusercontent.com/6964288/46190802-9d008d00-c327-11e8-8813-73e1424c39da.png)

**Comment by chungkwong** [comment]
如果你安装了排版系统TeX的发行版，在安装目录里面应该有上面这些字体（除最后三个字体见 http://ftp.gnu.org/gnu/freefont/ ，它们不是排版专用字体，只是支持字符较多，用来补漏）。在Linux下如果用apt安装texlive，应该就在上述位置，否则可以尝试用locate命令找如`locate cmmi10`。另外也可在CTAN找，比如 https://www.ctan.org/tex-archive/fonts/cm/ps-type1/bakoma/pfb 或 https://www.ctan.org/tex-archive/fonts/cm-unicode/fonts/otf 中有主要的字体。

另外，也可以把这些路径改为其它字体的路径（前提是每个需要识别的字符都可以从至少一个字体取得），只支持Truetype或Type 1格式。
